# Generated by Django 4.2.16 on 2024-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('location', models.CharField(choices=[('US/Canada', 'United States/Canada'), ('UK', 'United Kingdom'), ('EU', 'European Union'), ('AUS/NZ', 'Australia/New Zealand'), ('APAC', 'Asia-Pacific (APAC)'), ('ME', 'Middle East'), ('AF', 'Africa')], default='US/Canada', max_length=50)),
                ('skills', models.TextField()),
            ],
        ),
    ]
